css-anim:
	svgtiler css-anim.css shapes.coffee css-anim.csv
	svgtiler css-anim.css ascii.coffee ascii.asc
styl-anim:
	svgtiler css-anim.styl shapes.coffee css-anim.csv
	svgtiler css-anim.styl ascii.coffee ascii.asc
