all: castle underground underwater overworld

castle:
	svgtiler -f -P palette_castle.js -O door_castle mario.coffee door.tsv

overworld:
	svgtiler -f -P palette_overworld.js -O door_overworld mario.coffee door.tsv

underground:
	svgtiler -f -P palette_underground.js -O door_underground mario.coffee door.tsv

underwater:
	svgtiler -f -P palette_underwater.js -O door_underwater mario.coffee door.tsv
