all: castle underground underwater overworld

castle:
	svgtiler -f -P palette_castle.js -O \*_castle mario.coffee door.tsv

overworld:
	svgtiler -f -P palette_overworld.js -O \*_overworld mario.coffee door.tsv

underground:
	svgtiler -f -P palette_underground.js -O \*_underground mario.coffee door.tsv

underwater:
	svgtiler -f -P palette_underwater.js -O \*_underwater mario.coffee door.tsv
